#include "scripting/lua-bindings/auto/CCRegisterLuaUIAuto.hpp"
#include "ui/CocosGUI.h"
extern void RegisterLuaUILayoutParameterAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUILinearLayoutParameterAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIRelativeLayoutParameterAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIWidgetAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUILayoutAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIButtonAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIAbstractCheckButtonAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUICheckBoxAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIRadioButtonAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIRadioButtonGroupAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIImageViewAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUITextAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUITextAtlasAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUILoadingBarAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIScrollViewAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIListViewAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUISliderAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUITextFieldAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUITextBMFontAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIPageViewAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIHelperAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIRichElementAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIRichElementTextAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIRichElementImageAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIRichElementCustomNodeAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIRichElementNewLineAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIRichTextAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIHBoxAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIVBoxAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIRelativeBoxAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIVideoPlayerAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIWebViewAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIScale9SpriteAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIEditBoxAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUILayoutComponentAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUITabHeaderAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUITabControlAuto(cocos2d::extension::Lua&);
extern void RegisterLuaUIQrCodeAuto(cocos2d::extension::Lua&);
void RegisterLuaUIAuto(cocos2d::extension::Lua& lua){
lua["ccui"]=lua.get_or("ccui",lua.create_table());
RegisterLuaUILayoutParameterAuto(lua);
RegisterLuaUILinearLayoutParameterAuto(lua);
RegisterLuaUIRelativeLayoutParameterAuto(lua);
RegisterLuaUIWidgetAuto(lua);
RegisterLuaUILayoutAuto(lua);
RegisterLuaUIButtonAuto(lua);
RegisterLuaUIAbstractCheckButtonAuto(lua);
RegisterLuaUICheckBoxAuto(lua);
RegisterLuaUIRadioButtonAuto(lua);
RegisterLuaUIRadioButtonGroupAuto(lua);
RegisterLuaUIImageViewAuto(lua);
RegisterLuaUITextAuto(lua);
RegisterLuaUITextAtlasAuto(lua);
RegisterLuaUILoadingBarAuto(lua);
RegisterLuaUIScrollViewAuto(lua);
RegisterLuaUIListViewAuto(lua);
RegisterLuaUISliderAuto(lua);
RegisterLuaUITextFieldAuto(lua);
RegisterLuaUITextBMFontAuto(lua);
RegisterLuaUIPageViewAuto(lua);
RegisterLuaUIHelperAuto(lua);
RegisterLuaUIRichElementAuto(lua);
RegisterLuaUIRichElementTextAuto(lua);
RegisterLuaUIRichElementImageAuto(lua);
RegisterLuaUIRichElementCustomNodeAuto(lua);
RegisterLuaUIRichElementNewLineAuto(lua);
RegisterLuaUIRichTextAuto(lua);
RegisterLuaUIHBoxAuto(lua);
RegisterLuaUIVBoxAuto(lua);
RegisterLuaUIRelativeBoxAuto(lua);
RegisterLuaUIVideoPlayerAuto(lua);
RegisterLuaUIWebViewAuto(lua);
RegisterLuaUIScale9SpriteAuto(lua);
RegisterLuaUIEditBoxAuto(lua);
RegisterLuaUILayoutComponentAuto(lua);
RegisterLuaUITabHeaderAuto(lua);
RegisterLuaUITabControlAuto(lua);
RegisterLuaUIQrCodeAuto(lua);
}