#include "scripting/lua-bindings/auto/CCRegisterLuaStudioAuto.hpp"
#include "cocostudio/CocoStudio.h"
#include "cocostudio/CCComExtensionData.h"
namespace cocos2d{
extern void RegisterLuaStudioActionFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioActionMoveFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioActionScaleFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioActionRotationFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioActionFadeFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioActionTintFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioActionObjectAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioActionManagerExAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioBaseDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioDisplayDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioSpriteDisplayDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioArmatureDisplayDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioParticleDisplayDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioBoneDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioArmatureDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioFrameDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioMovementBoneDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioMovementDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioAnimationDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioContourDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioTextureDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioTweenAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioDisplayManagerAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioBoneAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioBatchNodeAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioMovementEventTypeAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioArmatureAnimationAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioArmatureDataManagerAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioArmatureAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioSkinAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioComAttributeAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioComAudioAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioComControllerAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioComRenderAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioGUIReaderAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioSceneReaderAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioActionTimelineCacheAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioVisibleFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioTextureFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioRotationFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioSkewFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioRotationSkewFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioPositionFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioScaleFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioAnchorPointFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioInnerActionTypeAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioInnerActionFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioColorFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioAlphaFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioEventFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioZOrderFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioBlendFuncFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioPlayableFrameAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioTimelineAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioActionTimelineDataAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioActionTimelineAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioActionTimelineNodeAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioBoneNodeAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioSkeletonNodeAuto(cocos2d::extension::Lua&);
extern void RegisterLuaStudioComExtensionDataAuto(cocos2d::extension::Lua&);
void RegisterLuaStudioAuto(cocos2d::extension::Lua& lua){
lua["ccs"]=lua.get_or("ccs",lua.create_table());
RegisterLuaStudioActionFrameAuto(lua);
RegisterLuaStudioActionMoveFrameAuto(lua);
RegisterLuaStudioActionScaleFrameAuto(lua);
RegisterLuaStudioActionRotationFrameAuto(lua);
RegisterLuaStudioActionFadeFrameAuto(lua);
RegisterLuaStudioActionTintFrameAuto(lua);
RegisterLuaStudioActionObjectAuto(lua);
RegisterLuaStudioActionManagerExAuto(lua);
RegisterLuaStudioBaseDataAuto(lua);
RegisterLuaStudioDisplayDataAuto(lua);
RegisterLuaStudioSpriteDisplayDataAuto(lua);
RegisterLuaStudioArmatureDisplayDataAuto(lua);
RegisterLuaStudioParticleDisplayDataAuto(lua);
RegisterLuaStudioBoneDataAuto(lua);
RegisterLuaStudioArmatureDataAuto(lua);
RegisterLuaStudioFrameDataAuto(lua);
RegisterLuaStudioMovementBoneDataAuto(lua);
RegisterLuaStudioMovementDataAuto(lua);
RegisterLuaStudioAnimationDataAuto(lua);
RegisterLuaStudioContourDataAuto(lua);
RegisterLuaStudioTextureDataAuto(lua);
RegisterLuaStudioTweenAuto(lua);
RegisterLuaStudioDisplayManagerAuto(lua);
RegisterLuaStudioBoneAuto(lua);
RegisterLuaStudioBatchNodeAuto(lua);
RegisterLuaStudioMovementEventTypeAuto(lua);
RegisterLuaStudioArmatureAnimationAuto(lua);
RegisterLuaStudioArmatureDataManagerAuto(lua);
RegisterLuaStudioArmatureAuto(lua);
RegisterLuaStudioSkinAuto(lua);
RegisterLuaStudioComAttributeAuto(lua);
RegisterLuaStudioComAudioAuto(lua);
RegisterLuaStudioComControllerAuto(lua);
RegisterLuaStudioComRenderAuto(lua);
RegisterLuaStudioGUIReaderAuto(lua);
RegisterLuaStudioSceneReaderAuto(lua);
RegisterLuaStudioActionTimelineCacheAuto(lua);
RegisterLuaStudioFrameAuto(lua);
RegisterLuaStudioVisibleFrameAuto(lua);
RegisterLuaStudioTextureFrameAuto(lua);
RegisterLuaStudioRotationFrameAuto(lua);
RegisterLuaStudioSkewFrameAuto(lua);
RegisterLuaStudioRotationSkewFrameAuto(lua);
RegisterLuaStudioPositionFrameAuto(lua);
RegisterLuaStudioScaleFrameAuto(lua);
RegisterLuaStudioAnchorPointFrameAuto(lua);
RegisterLuaStudioInnerActionTypeAuto(lua);
RegisterLuaStudioInnerActionFrameAuto(lua);
RegisterLuaStudioColorFrameAuto(lua);
RegisterLuaStudioAlphaFrameAuto(lua);
RegisterLuaStudioEventFrameAuto(lua);
RegisterLuaStudioZOrderFrameAuto(lua);
RegisterLuaStudioBlendFuncFrameAuto(lua);
RegisterLuaStudioPlayableFrameAuto(lua);
RegisterLuaStudioTimelineAuto(lua);
RegisterLuaStudioActionTimelineDataAuto(lua);
RegisterLuaStudioActionTimelineAuto(lua);
RegisterLuaStudioActionTimelineNodeAuto(lua);
RegisterLuaStudioBoneNodeAuto(lua);
RegisterLuaStudioSkeletonNodeAuto(lua);
RegisterLuaStudioComExtensionDataAuto(lua);
}
}